<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNlvzzos\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNlvzzos/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNlvzzos.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNlvzzos\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNlvzzos\appDevDebugProjectContainer([
    'container.build_hash' => 'Nlvzzos',
    'container.build_id' => '365de3ad',
    'container.build_time' => 1726769938,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNlvzzos');
