<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0suanb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0suanb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX0suanb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX0suanb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX0suanb\appDevDebugProjectContainer([
    'container.build_hash' => 'X0suanb',
    'container.build_id' => 'ab65e0df',
    'container.build_time' => 1727347150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0suanb');
